//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeHack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeHack.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Stench
        ///2,Drizzle
        ///3,Speed Boost
        ///4,Battle Armor
        ///5,Sturdy
        ///6,Damp
        ///7,Limber
        ///8,Sand Veil
        ///9,Static
        ///10,Volt Absorb
        ///11,Water Absorb
        ///12,Oblivious
        ///13,Cloud Nine
        ///14,Compoundeyes
        ///15,Insomnia
        ///16,Color Change
        ///17,Immunity
        ///18,Flash Fire
        ///19,Shield Dust
        ///20,Own Tempo
        ///21,Suction Cups
        ///22,Intimidate
        ///23,Shadow Tag
        ///24,Rough Skin
        ///25,Wonder Guard
        ///26,Levitate
        ///27,Effect Spore
        ///28,Synchronize
        ///29,Clear Body
        ///30,Natural Cure
        ///31,Lightningrod
        ///32,Serene Grace
        ///33,Swift Swim
        ///34,Chlorophyll
        ///35,Illuminate
        ///36,Trace
        ///37,Huge Power
        ///38,Poison Point
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string abilities {
            get {
                return ResourceManager.GetString("abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001=3000
        ///0002=3041
        ///0003=3042
        ///0004=3043
        ///0005=3044
        ///0006=3045
        ///0007=3046
        ///0008=3047
        ///0009=3048
        ///000A=3049
        ///000B=304A
        ///000C=304B
        ///000D=304C
        ///000E=304D
        ///000F=304E
        ///0010=304F
        ///0011=3050
        ///0012=3051
        ///0013=3052
        ///0014=3053
        ///0015=3054
        ///0016=3055
        ///0017=3056
        ///0018=3057
        ///0019=3058
        ///001A=3059
        ///001B=305A
        ///001C=305B
        ///001D=305C
        ///001E=305D
        ///001F=305E
        ///0020=305F
        ///0021=3060
        ///0022=3061
        ///0023=3062
        ///0024=3063
        ///0025=3064
        ///0026=3065
        ///0027=3066
        ///0028=3067
        ///0029=3068
        ///002A=3069
        ///002B=306A
        ///002C=306B
        ///002D=306C
        ///002E=306D
        ///002F=3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chartable {
            get {
                return ResourceManager.GetString("chartable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Ball 
        ///Ultra Ball 
        ///Great Ball 
        ///Poké Ball 
        ///Safari Ball 
        ///Net Ball 
        ///Dive Ball 
        ///Nest Ball 
        ///Repeat Ball 
        ///Timer Ball 
        ///Luxury Ball 
        ///Premier Ball 
        ///Dusk Ball 
        ///Heal Ball 
        ///Quick Ball 
        ///Cherish Ball 
        ///Potion 
        ///Antidote 
        ///Burn Heal 
        ///Ice Heal 
        ///Awakening 
        ///Parlyz Heal 
        ///Full Restore 
        ///Max Potion 
        ///Hyper Potion 
        ///Super Potion 
        ///Full Heal 
        ///Revive 
        ///Max Revive 
        ///Fresh Water 
        ///Soda Pop 
        ///Lemonade 
        ///Moomoo Milk 
        ///EnergyPowder 
        ///Energy Root 
        ///Heal Powder 
        ///Revival Herb 
        ///Ether 
        ///Max Ether 
        ///Elixir 
        ///Max E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound
        ///Karate Chop
        ///DoubleSlap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///ThunderPunch
        ///Scratch
        ///ViceGrip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand-Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///SonicBoom
        ///Disable
        ///Aci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moves {
            get {
                return ResourceManager.GetString("moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Bulbasaur,45,49,49,65,65,45,3,0,31
        ///2,Ivysaur,60,62,63,80,80,60,3,0,31
        ///3,Venusaur,80,82,83,100,100,80,3,0,31
        ///4,Charmander,39,52,43,60,50,65,3,0,31
        ///5,Charmeleon,58,64,58,80,65,80,3,0,31
        ///6,Charizard,78,84,78,109,85,100,3,0,31
        ///7,Squirtle,44,48,65,50,64,43,3,0,31
        ///8,Wartortle,59,63,80,65,60,58,3,0,31
        ///9,Blastoise,79,83,100,85,105,78,3,0,31
        ///10,Caterpie,45,30,35,20,20,45,0,0,127
        ///11,Metapod,50,20,55,25,25,30,0,0,127
        ///12,Butterfree,60,45,50,80,80,70,0,0,127
        ///13,Weedle,40,35,30,20,20,50,0,0,127
        ///14,Kakuna,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pokedata {
            get {
                return ResourceManager.GetString("pokedata", resourceCulture);
            }
        }
    }
}
