//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiny2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shiny2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Log.
        /// </summary>
        internal static string DnsLog {
            get {
                return ResourceManager.GetString("DnsLog", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon favicon_16x16 {
            get {
                object obj = ResourceManager.GetObject("favicon_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon favicon_32x32 {
            get {
                object obj = ResourceManager.GetObject("favicon_32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder to distribute.
        /// </summary>
        internal static string FolderDistribute {
            get {
                return ResourceManager.GetString("FolderDistribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save Pokemon to.
        /// </summary>
        internal static string FolderSave {
            get {
                return ResourceManager.GetString("FolderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTS Log.
        /// </summary>
        internal static string GtsLog {
            get {
                return ResourceManager.GetString("GtsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini&amp;tialize GTS.
        /// </summary>
        internal static string GtsStart {
            get {
                return ResourceManager.GetString("GtsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop GTS.
        /// </summary>
        internal static string GtsStop {
            get {
                return ResourceManager.GetString("GtsStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful Hints.
        /// </summary>
        internal static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image File....
        /// </summary>
        internal static string ImgAdd {
            get {
                return ResourceManager.GetString("ImgAdd", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon jirachi_128 {
            get {
                object obj = ResourceManager.GetObject("jirachi_128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pkm Files|*.pkm.
        /// </summary>
        internal static string PkmFilter {
            get {
                return ResourceManager.GetString("PkmFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Pokemon File.
        /// </summary>
        internal static string SelectPkm {
            get {
                return ResourceManager.GetString("SelectPkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros:
        ///
        ///$hg$ - Display the number of sent gen IV pokemon
        ///$bw$ - Display the number of sent gen V pokemon
        ///$mode$ - Display the current mode [distribution/receiving]
        ///$stime$ - Display the current system time [short]
        ///$ltime$ - Display the current system time [long]
        ///$sdate$ - Display the current system date [short]
        ///$ldate$ - Display the current system date [long]
        ///
        ///$cgen4$ - current gen 4 file pokemon [only applicable in file mode]
        ///$cgen5$ - current gen 5 file pokemon [only applicable in file mode]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string special_codes {
            get {
                return ResourceManager.GetString("special_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Initialize DNS.
        /// </summary>
        internal static string StartDns {
            get {
                return ResourceManager.GetString("StartDns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop DNS.
        /// </summary>
        internal static string StopDns {
            get {
                return ResourceManager.GetString("StopDns", resourceCulture);
            }
        }
    }
}
